assetKey: mod_landscape_02
heightFull: 100.2811
spawnPaddingEdge: 100
spawnPaddingGroup: 25
spawnInterval: 25
spawnNormalThreshold: 0.97
spawnHeightMin: 0.086
spawnHeightMax: 0.881
navSlopeLimit: 25
propNormalDotRange:
  x: 0.1
  y: 0.98
spawnsGeneral:
- x: -300
  y: 15.11059
  z: 0
- x: -275
  y: 12.80137
  z: -100
- x: -275
  y: 13.25023
  z: -75
- x: -275
  y: 13.32204
  z: -50
- x: -275
  y: 14.25276
  z: -25
- x: -275
  y: 14.94593
  z: 9.313226E-08
- x: -275
  y: 15.77056
  z: 25
- x: -275
  y: 16.54093
  z: 50
- x: -275
  y: 17.99289
  z: 75
- x: -275
  y: 19.8633
  z: 100
- x: -250
  y: 12.10128
  z: -150
- x: -250
  y: 12.12227
  z: -125
- x: -250
  y: 10.71827
  z: -99.99999
- x: -250
  y: 12.53809
  z: -75
- x: -250
  y: 13.6235
  z: -50
- x: -250
  y: 14.41608
  z: -25
- x: -250
  y: 15.14172
  z: -4.656613E-07
- x: -250
  y: 15.92554
  z: 25
- x: -250
  y: 16.6372
  z: 50
- x: -250
  y: 17.78523
  z: 75
- x: -250
  y: 19.32286
  z: 100
- x: -250
  y: 20.95268
  z: 125
- x: -250
  y: 22.43542
  z: 150
- x: -225
  y: 13.19925
  z: -175
- x: -225
  y: 13.64844
  z: -150
- x: -225
  y: 13.39402
  z: -125
- x: -225
  y: 12.47489
  z: -100
- x: -225
  y: 13.43351
  z: -74.99999
- x: -225
  y: 14.2179
  z: -50
- x: -225
  y: 15.00735
  z: -25
- x: -225
  y: 15.80403
  z: -3.72529E-07
- x: -225
  y: 16.95513
  z: 25
- x: -225
  y: 17.31175
  z: 50
- x: -225
  y: 18.22623
  z: 75
- x: -225
  y: 19.22175
  z: 100
- x: -225
  y: 21.04734
  z: 125
- x: -225
  y: 22.42426
  z: 150
- x: -225
  y: 23.13507
  z: 175
- x: -200
  y: 12.97747
  z: -200
- x: -200
  y: 14.05955
  z: -175
- x: -200
  y: 13.79991
  z: -150
- x: -200
  y: 13.65722
  z: -125
- x: -200
  y: 13.31804
  z: -100
- x: -200
  y: 14.69428
  z: -50
- x: -200
  y: 15.81424
  z: -25
- x: -200
  y: 17.20633
  z: -1.862645E-07
- x: -200
  y: 18.31192
  z: 25
- x: -200
  y: 18.87477
  z: 50
- x: -200
  y: 20.08497
  z: 75
- x: -200
  y: 20.0524
  z: 100
- x: -200
  y: 21.283
  z: 125
- x: -200
  y: 22.09763
  z: 150
- x: -200
  y: 22.96118
  z: 175
- x: -200
  y: 22.90152
  z: 200
- x: -175
  y: 11.87874
  z: -225
- x: -175
  y: 13.30076
  z: -200
- x: -175
  y: 14.19066
  z: -175
- x: -175
  y: 14.1937
  z: -150
- x: -175
  y: 13.80112
  z: -125
- x: -175
  y: 13.88293
  z: -100
- x: -175
  y: 16.39237
  z: -50
- x: -175
  y: 17.92764
  z: -25
- x: -175
  y: 19.06078
  z: -2.328306E-08
- x: -175
  y: 21.01258
  z: 25
- x: -175
  y: 21.55794
  z: 50
- x: -175
  y: 22.47839
  z: 100
- x: -175
  y: 22.05079
  z: 125
- x: -175
  y: 22.89138
  z: 150
- x: -175
  y: 22.87279
  z: 175
- x: -175
  y: 22.5868
  z: 200
- x: -175
  y: 22.46512
  z: 225
- x: -150
  y: 10.65882
  z: -250
- x: -150
  y: 12.70809
  z: -225
- x: -150
  y: 14.00381
  z: -200
- x: -150
  y: 14.83367
  z: -175
- x: -150
  y: 14.02096
  z: -150
- x: -150
  y: 14.05424
  z: -125
- x: -150
  y: 14.65126
  z: -100
- x: -150
  y: 15.89489
  z: -75.00001
- x: -150
  y: 17.66002
  z: -50
- x: -150
  y: 25.21286
  z: 100
- x: -150
  y: 23.5965
  z: 125
- x: -150
  y: 24.10095
  z: 150
- x: -150
  y: 23.43545
  z: 175
- x: -150
  y: 22.9531
  z: 200
- x: -150
  y: 22.47653
  z: 225
- x: -150
  y: 22.10641
  z: 250
- x: -125
  y: 8.812591
  z: -250
- x: -125
  y: 10.79181
  z: -225
- x: -125
  y: 12.65965
  z: -200
- x: -125
  y: 13.39422
  z: -175
- x: -125
  y: 13.67337
  z: -150
- x: -125
  y: 14.63273
  z: -125
- x: -125
  y: 16.26705
  z: -100
- x: -125
  y: 19.55176
  z: -75
- x: -125
  y: 26.03597
  z: 150
- x: -125
  y: 24.64623
  z: 175
- x: -125
  y: 23.51287
  z: 200
- x: -125
  y: 22.80315
  z: 225
- x: -125
  y: 22.34784
  z: 250
- x: -100
  y: 9.14998
  z: -225
- x: -100
  y: 10.88119
  z: -200
- x: -100
  y: 11.92203
  z: -175
- x: -100
  y: 13.79064
  z: -150
- x: -100
  y: 16.5211
  z: -125
- x: -100
  y: 28.37848
  z: 150
- x: -100
  y: 25.74064
  z: 175
- x: -100
  y: 23.59776
  z: 225
- x: -99.99999
  y: 22.9319
  z: 250
- x: -100
  y: 22.42243
  z: 275
- x: -75
  y: 9.004911
  z: -225
- x: -75
  y: 9.643993
  z: -200
- x: -75
  y: 11.47539
  z: -175
- x: -75
  y: 14.64501
  z: -150
- x: -75
  y: 30.71531
  z: 150
- x: -75
  y: 24.63474
  z: 225
- x: -75
  y: 24.22636
  z: 250
- x: -75
  y: 23.40266
  z: 275
- x: -50
  y: 9.943763
  z: -275
- x: -50
  y: 10.30732
  z: -250
- x: -50
  y: 9.754448
  z: -225
- x: -50
  y: 10.71634
  z: -200
- x: -50
  y: 12.23726
  z: -175
- x: -50
  y: 14.63433
  z: -150
- x: -50
  y: 29.44788
  z: 175
- x: -50
  y: 27.3232
  z: 200
- x: -50
  y: 26.39135
  z: 225
- x: -50
  y: 26.32819
  z: 250
- x: -50
  y: 24.60461
  z: 275
- x: -25
  y: 11.27031
  z: -275
- x: -25
  y: 11.75023
  z: -250
- x: -25
  y: 11.46176
  z: -225
- x: -25
  y: 11.90979
  z: -200
- x: -25
  y: 14.00903
  z: -175
- x: -25
  y: 17.03553
  z: -150
- x: -25
  y: 30.88636
  z: 175
- x: -25
  y: 28.53816
  z: 200
- x: -25
  y: 28.39904
  z: 225
- x: -25
  y: 27.3306
  z: 250
- x: -25
  y: 26.36678
  z: 275
- x: 1.484295E-07
  y: 11.78438
  z: -300
- x: 4.656613E-08
  y: 13.15989
  z: -275
- x: -6.402843E-08
  y: 14.01915
  z: -250
- x: -1.629815E-07
  y: 13.48702
  z: -225
- x: -1.862645E-07
  y: 14.56747
  z: -200
- x: 3.72529E-07
  y: 18.95613
  z: -150
- x: -2.153683E-07
  y: 31.46081
  z: 175
- x: -9.313226E-08
  y: 30.37215
  z: 200
- x: -2.095476E-07
  y: 29.83893
  z: 225
- x: -2.037268E-07
  y: 28.62351
  z: 250
- x: -9.313226E-08
  y: 27.48663
  z: 275
- x: 25
  y: 13.25126
  z: -275
- x: 25
  y: 15.61057
  z: -250
- x: 25
  y: 16.11576
  z: -225
- x: 25
  y: 16.71846
  z: -200
- x: 25
  y: 35.40387
  z: 150
- x: 25
  y: 32.6373
  z: 175
- x: 25
  y: 31.55
  z: 200
- x: 25
  y: 30.4002
  z: 225
- x: 25
  y: 30.03524
  z: 250
- x: 25
  y: 29.16958
  z: 275
- x: 50
  y: 14.87711
  z: -275
- x: 50
  y: 15.93893
  z: -250
- x: 50
  y: 17.56885
  z: -225
- x: 50
  y: 19.37238
  z: -200
- x: 50
  y: 21.0626
  z: -175
- x: 50
  y: 24.59101
  z: -150
- x: 50
  y: 35.35051
  z: 150
- x: 50
  y: 33.05221
  z: 175
- x: 50
  y: 31.77661
  z: 200
- x: 50
  y: 30.70183
  z: 225
- x: 50
  y: 30.06619
  z: 250
- x: 50
  y: 27.97337
  z: 275
- x: 75
  y: 15.56145
  z: -275
- x: 75
  y: 16.72572
  z: -250
- x: 75
  y: 18.63909
  z: -225
- x: 75
  y: 19.97525
  z: -200
- x: 75
  y: 21.73792
  z: -175
- x: 75.00001
  y: 23.67038
  z: -150
- x: 75
  y: 35.66831
  z: 125
- x: 75
  y: 34.36713
  z: 150
- x: 75
  y: 32.98843
  z: 175
- x: 75
  y: 31.99102
  z: 200
- x: 75
  y: 30.49577
  z: 225
- x: 75
  y: 28.84084
  z: 250
- x: 75.00001
  y: 27.3611
  z: 275
- x: 100
  y: 14.70586
  z: -275
- x: 100
  y: 16.08619
  z: -250
- x: 100
  y: 17.74773
  z: -225
- x: 100
  y: 19.51723
  z: -200
- x: 99.99999
  y: 21.6408
  z: -175
- x: 100
  y: 23.1981
  z: -150
- x: 100
  y: 25.23488
  z: -125
- x: 100
  y: 28.46484
  z: -99.99999
- x: 100
  y: 33.1591
  z: 125
- x: 100
  y: 32.66511
  z: 150
- x: 100
  y: 32.42669
  z: 175
- x: 100
  y: 31.60645
  z: 200
- x: 99.99999
  y: 29.96297
  z: 225
- x: 100
  y: 28.50623
  z: 250
- x: 100
  y: 27.08266
  z: 275
- x: 125
  y: 16.58492
  z: -250
- x: 125
  y: 18.35116
  z: -225
- x: 125
  y: 19.22166
  z: -200
- x: 125
  y: 20.47206
  z: -175
- x: 125
  y: 22.25236
  z: -150
- x: 125
  y: 24.28191
  z: -125
- x: 125
  y: 26.60853
  z: -100
- x: 125
  y: 27.67474
  z: -74.99999
- x: 125
  y: 27.87947
  z: -50
- x: 125
  y: 31.8285
  z: 75
- x: 125
  y: 31.22022
  z: 100
- x: 125
  y: 31.29311
  z: 125
- x: 125
  y: 31.34652
  z: 150
- x: 125
  y: 31.36366
  z: 175
- x: 125
  y: 30.9591
  z: 200
- x: 125
  y: 30.09791
  z: 225
- x: 125
  y: 28.51223
  z: 250
- x: 150
  y: 16.49443
  z: -250
- x: 150
  y: 19.07998
  z: -225
- x: 150
  y: 21.32332
  z: -200
- x: 150
  y: 21.99292
  z: -175
- x: 150
  y: 24.77942
  z: -100
- x: 150
  y: 25.08434
  z: -75.00001
- x: 150
  y: 24.93793
  z: -50
- x: 150
  y: 25.81728
  z: -25
- x: 150
  y: 27.29152
  z: 9.313226E-08
- x: 150
  y: 28.69161
  z: 25
- x: 150
  y: 29.1773
  z: 50
- x: 150
  y: 29.03584
  z: 75
- x: 150
  y: 29.33974
  z: 100
- x: 150
  y: 29.87995
  z: 125
- x: 150
  y: 30.69834
  z: 150
- x: 150
  y: 30.82515
  z: 175
- x: 150
  y: 30.0553
  z: 200
- x: 150
  y: 29.63059
  z: 225
- x: 150
  y: 27.69092
  z: 250
- x: 175
  y: 18.86328
  z: -225
- x: 175
  y: 21.32415
  z: -200
- x: 175
  y: 22.87529
  z: -175
- x: 175
  y: 23.48026
  z: -150
- x: 175
  y: 23.43602
  z: -125
- x: 175
  y: 24.1757
  z: -100
- x: 175
  y: 24.32152
  z: -75
- x: 175
  y: 24.02767
  z: -50
- x: 175
  y: 24.41268
  z: -25
- x: 175
  y: 25.06251
  z: 3.259629E-07
- x: 175
  y: 25.84045
  z: 25
- x: 175
  y: 26.9069
  z: 50
- x: 175
  y: 27.47402
  z: 74.99999
- x: 175
  y: 28.30604
  z: 100
- x: 175
  y: 28.887
  z: 125
- x: 175
  y: 29.6044
  z: 150
- x: 175
  y: 29.50589
  z: 175
- x: 175
  y: 28.80701
  z: 200
- x: 175
  y: 28.19766
  z: 225
- x: 200
  y: 19.78505
  z: -200
- x: 200
  y: 21.18375
  z: -175
- x: 200
  y: 22.93891
  z: -150
- x: 200
  y: 23.78513
  z: -125
- x: 200
  y: 24.02427
  z: -100
- x: 200
  y: 23.82974
  z: -75
- x: 200
  y: 23.1806
  z: -50
- x: 200
  y: 23.51462
  z: -25
- x: 200
  y: 24.90882
  z: 25
- x: 200
  y: 25.88575
  z: 50
- x: 200
  y: 26.43617
  z: 75
- x: 200
  y: 27.1968
  z: 100
- x: 200
  y: 27.86385
  z: 125
- x: 200
  y: 28.46355
  z: 150
- x: 200
  y: 28.05553
  z: 175
- x: 200
  y: 27.72727
  z: 200
- x: 225
  y: 20.61491
  z: -175
- x: 225
  y: 23.18211
  z: -150
- x: 225
  y: 23.87107
  z: -125
- x: 225
  y: 24.25947
  z: -100
- x: 225
  y: 22.55041
  z: -75
- x: 225
  y: 22.11827
  z: -50
- x: 225
  y: 24.80789
  z: 25
- x: 225
  y: 25.55519
  z: 50
- x: 225
  y: 27.48346
  z: 125
- x: 225
  y: 28.04579
  z: 150
- x: 225
  y: 27.33396
  z: 175
- x: 250
  y: 20.71903
  z: -150
- x: 250
  y: 22.3126
  z: -125
- x: 250
  y: 22.88529
  z: -100
- x: 250
  y: 20.23961
  z: -75
- x: 250
  y: 22.80621
  z: -50
- x: 250
  y: 23.70688
  z: -25
- x: 250
  y: 24.44135
  z: 0
- x: 250
  y: 25.23551
  z: 25
- x: 250
  y: 26.47483
  z: 50
- x: 250
  y: 26.64923
  z: 75
- x: 250
  y: 26.96699
  z: 100
- x: 250
  y: 26.69022
  z: 125
- x: 250
  y: 27.07136
  z: 150
- x: 275
  y: 19.72736
  z: -75
- x: 275
  y: 23.33233
  z: -50
- x: 275
  y: 24.92543
  z: -25
- x: 275
  y: 25.48216
  z: 0
- x: 275
  y: 26.487
  z: 25
- x: 275
  y: 27.10354
  z: 50
- x: 275
  y: 27.47139
  z: 75
- x: 275
  y: 26.56043
  z: 100
pointGroups:
  border:
    points:
    - x: 297.9773
      y: 24.66704
      z: -18.88025
    - x: 1.718811
      y: 28.93722
      z: 253.5268
    - x: -311.6828
      y: 13.82374
      z: -95.00752
    - x: 32.22937
      y: 10.89176
      z: -319.0566
  border_exit:
    points:
    - x: 1.530243
      y: 13.66227
      z: -209.0049
  midpoint:
    points:
    - x: 131.6054
      y: 26.89303
      z: -58.00429
  poi:
    points:
    - x: 166.9538
      y: 19.37276
      z: -223.2277
    - x: 277.6512
      y: 26.54389
      z: 26.4194
    - x: 123.0966
      y: 31.76379
      z: 167.3443
    - x: -163.332
      y: 22.99846
      z: 178.8994
    - x: -225.7048
      y: 15.68916
      z: -2.777184
    - x: -152.8221
      y: 14.28096
      z: -188.5055
    - x: 26.62706
      y: 13.58771
      z: -274.2521
layers:
- heightNormalized: 0
  temperature:
    f: 1
  precipitationFactors:
    v:
      x: 0.15
      y: 0.2
      z: 0.35
  biome:
    tagsUsed: true
    keys: 
    tags:
      mossy_dry: true
- heightNormalized: 0.5
  temperature:
    f: -1
  precipitationFactors:
    v:
      x: 0.3
      y: 0.1
      z: 0.5
  biome:
    tagsUsed: true
    keys: 
    tags:
      alpine_light: true
- heightNormalized: 0.66
  temperature:
    f: -1
  precipitationFactors:
    v:
      x: 0.3
      y: 0.1
      z: 0.5
  biome:
    tagsUsed: true
    keys: 
    tags:
      alpine_heavy: true
