assetKey: mod_landscape_01
heightFull: 85.67078
spawnPaddingEdge: 80
spawnPaddingGroup: 25
spawnInterval: 25
spawnNormalThreshold: 0.95
spawnHeightMin: 0
spawnHeightMax: 0.6
navSlopeLimit: 20
propNormalDotRange:
  x: 0.8
  y: 0.97
spawnsGeneral:
- x: -295
  y: 41.4057
  z: -120
- x: -295
  y: 39.89558
  z: -95.00001
- x: -295
  y: 40.97961
  z: -70
- x: -295
  y: 40.9108
  z: -45
- x: -295
  y: 39.31681
  z: -20
- x: -295
  y: 38.45655
  z: 5
- x: -295
  y: 39.07793
  z: 30
- x: -295
  y: 40.08271
  z: 55
- x: -295
  y: 40.90282
  z: 80
- x: -270
  y: 44.22974
  z: -170
- x: -270
  y: 42.56011
  z: -145
- x: -270
  y: 40.65611
  z: -120
- x: -270
  y: 38.96664
  z: -94.99999
- x: -270
  y: 39.8606
  z: -45
- x: -270
  y: 37.22805
  z: -20
- x: -270
  y: 37.7306
  z: 30
- x: -270
  y: 39.13174
  z: 55
- x: -270
  y: 41.47949
  z: 79.99999
- x: -270
  y: 42.4439
  z: 155
- x: -245
  y: 45.55626
  z: -195
- x: -245
  y: 45.13804
  z: -170
- x: -245
  y: 43.52318
  z: -145
- x: -245
  y: 42.54508
  z: -120
- x: -245
  y: 38.06767
  z: -95
- x: -245
  y: 36.05792
  z: -70
- x: -245
  y: 35.54866
  z: -45
- x: -245
  y: 34.79451
  z: -20
- x: -245
  y: 40.56119
  z: 79.99999
- x: -245
  y: 41.96413
  z: 105
- x: -245
  y: 42.11037
  z: 130
- x: -245
  y: 42.25227
  z: 155
- x: -245
  y: 35.66896
  z: 205
- x: -220
  y: 36.78119
  z: -220
- x: -220
  y: 45.90772
  z: -170
- x: -220
  y: 44.62844
  z: -145
- x: -220
  y: 44.05584
  z: -120
- x: -220
  y: 39.16441
  z: -95
- x: -220
  y: 34.04547
  z: -69.99999
- x: -220
  y: 32.82699
  z: -45
- x: -220
  y: 32.37259
  z: -20
- x: -220
  y: 32.44735
  z: 5
- x: -220
  y: 32.65654
  z: 30
- x: -220
  y: 33.15391
  z: 55.00001
- x: -220
  y: 40.18964
  z: 105
- x: -220
  y: 41.89452
  z: 130
- x: -220
  y: 42.06962
  z: 155
- x: -220
  y: 39.52225
  z: 180
- x: -195
  y: 34.77742
  z: -245
- x: -195
  y: 35.56032
  z: -220
- x: -195
  y: 44.35328
  z: -170
- x: -195
  y: 43.95776
  z: -145
- x: -195
  y: 36.03374
  z: -95.00001
- x: -195
  y: 32.60339
  z: -70
- x: -195
  y: 31.52687
  z: -45
- x: -195
  y: 31.60471
  z: 5
- x: -195
  y: 32.07321
  z: 30
- x: -195
  y: 33.05082
  z: 55
- x: -195
  y: 34.5482
  z: 79.99999
- x: -195
  y: 37.41449
  z: 105
- x: -195
  y: 40.57509
  z: 130
- x: -195
  y: 42.29858
  z: 155
- x: -195
  y: 40.8773
  z: 180
- x: -195
  y: 44.4258
  z: 205
- x: -195
  y: 36.19348
  z: 230
- x: -170
  y: 35.32594
  z: -270
- x: -170
  y: 35.6357
  z: -245
- x: -170
  y: 43.27196
  z: -195
- x: -170
  y: 42.62029
  z: -170
- x: -170
  y: 42.29877
  z: -145
- x: -170
  y: 37.65788
  z: -120
- x: -170
  y: 33.90706
  z: -95
- x: -170
  y: 31.58371
  z: -70
- x: -170
  y: 31.00855
  z: -45
- x: -170
  y: 32.01121
  z: 5
- x: -170
  y: 33.13145
  z: 30
- x: -170
  y: 34.25407
  z: 55
- x: -170
  y: 35.73587
  z: 79.99999
- x: -170
  y: 38.78851
  z: 105
- x: -170
  y: 42.21884
  z: 130
- x: -170
  y: 43.33483
  z: 155
- x: -170
  y: 41.66895
  z: 205
- x: -170
  y: 36.65062
  z: 255
- x: -145
  y: 38.71653
  z: -245
- x: -145
  y: 41.87646
  z: -220
- x: -145
  y: 42.33532
  z: -195
- x: -145
  y: 41.19762
  z: -170
- x: -145
  y: 41.64804
  z: -145
- x: -145
  y: 37.40959
  z: -120
- x: -145
  y: 33.97298
  z: -95
- x: -145
  y: 32.73841
  z: -20
- x: -145
  y: 34.88665
  z: 5
- x: -145
  y: 36.3026
  z: 30
- x: -145
  y: 37.60168
  z: 55
- x: -145
  y: 38.77704
  z: 79.99999
- x: -145
  y: 39.35619
  z: 105
- x: -145
  y: 41.62764
  z: 130
- x: -145
  y: 43.35833
  z: 205
- x: -145
  y: 42.47209
  z: 230
- x: -145
  y: 40.12288
  z: 255
- x: -145
  y: 38.2232
  z: 280
- x: -120
  y: 34.23144
  z: -295
- x: -120
  y: 40.70915
  z: -245
- x: -120
  y: 41.69369
  z: -195
- x: -120
  y: 39.78783
  z: -170
- x: -120
  y: 40.56844
  z: -145
- x: -120
  y: 37.96381
  z: -120
- x: -120
  y: 35.76698
  z: -94.99999
- x: -120
  y: 33.25417
  z: -70.00001
- x: -120
  y: 31.00883
  z: -45
- x: -120
  y: 30.99399
  z: -20
- x: -120
  y: 33.38447
  z: 5
- x: -120
  y: 38.63051
  z: 55
- x: -120
  y: 39.16644
  z: 79.99999
- x: -120
  y: 40.93931
  z: 105
- x: -120
  y: 42.5927
  z: 130
- x: -120
  y: 44.16141
  z: 155
- x: -120
  y: 46.6371
  z: 180
- x: -120
  y: 42.90125
  z: 205
- x: -120
  y: 42.2247
  z: 230
- x: -120
  y: 41.03785
  z: 255
- x: -95
  y: 34.3788
  z: -295
- x: -95
  y: 38.1524
  z: -270
- x: -95
  y: 39.68419
  z: -195
- x: -94.99999
  y: 40.20911
  z: -170
- x: -95
  y: 33.84048
  z: -45
- x: -95
  y: 31.23499
  z: -20
- x: -94.99999
  y: 31.02235
  z: 5
- x: -95
  y: 32.18436
  z: 30
- x: -95
  y: 37.55659
  z: 79.99999
- x: -95.00001
  y: 40.29726
  z: 105
- x: -95
  y: 41.58382
  z: 130
- x: -95
  y: 45.13517
  z: 155
- x: -95
  y: 40.97562
  z: 205
- x: -95.00001
  y: 41.03728
  z: 230
- x: -95
  y: 39.82115
  z: 255
- x: -95
  y: 35.21334
  z: 280
- x: -70
  y: 34.12947
  z: -295
- x: -70
  y: 39.26665
  z: -270
- x: -70
  y: 39.04678
  z: -195
- x: -70
  y: 31.59946
  z: 5
- x: -70
  y: 30.78731
  z: 30
- x: -70
  y: 38.01581
  z: 105
- x: -70
  y: 38.37223
  z: 205
- x: -69.99999
  y: 37.73939
  z: 230
- x: -70
  y: 34.26955
  z: 255
- x: -69.99999
  y: 32.20007
  z: 280
- x: -45
  y: 33.32199
  z: -295
- x: -45
  y: 33.86063
  z: -270
- x: -45
  y: 35.36324
  z: -245
- x: -45
  y: 35.48669
  z: -220
- x: -45
  y: 37.93848
  z: -195
- x: -45
  y: 33.73703
  z: 105
- x: -45
  y: 34.7071
  z: 155
- x: -45
  y: 34.83526
  z: 180
- x: -45
  y: 32.65874
  z: 230
- x: -45
  y: 30.91697
  z: 255
- x: -45
  y: 32.48347
  z: 280
- x: -20
  y: 35.03838
  z: -270
- x: -20
  y: 34.2742
  z: -245
- x: -20
  y: 34.65437
  z: -220
- x: -20
  y: 36.72914
  z: -195
- x: -20
  y: 32.14104
  z: 30
- x: -20
  y: 30.7426
  z: 55
- x: -20
  y: 31.73556
  z: 105
- x: -20
  y: 32.34029
  z: 155
- x: -20
  y: 30.8245
  z: 180
- x: -20
  y: 31.63708
  z: 205
- x: -20
  y: 32.2773
  z: 230
- x: -20
  y: 35.15009
  z: 255
- x: 5
  y: 40.07884
  z: -295
- x: 5
  y: 39.03273
  z: -270
- x: 5
  y: 37.94759
  z: -245
- x: 5
  y: 34.79553
  z: -220
- x: 5
  y: 35.97181
  z: -195
- x: 5
  y: 59.35663
  z: -120
- x: 5
  y: 46.73888
  z: -20
- x: 5
  y: 39.41132
  z: 5
- x: 5
  y: 34.3669
  z: 30
- x: 5
  y: 32.05621
  z: 55
- x: 5
  y: 31.30922
  z: 79.99999
- x: 5
  y: 30.57557
  z: 105
- x: 5
  y: 31.01247
  z: 130
- x: 5
  y: 31.00387
  z: 155
- x: 5
  y: 31.97146
  z: 180
- x: 5
  y: 37.11353
  z: 205
- x: 5
  y: 38.17905
  z: 230
- x: 5
  y: 38.75924
  z: 255
- x: 5
  y: 40.29524
  z: 280
- x: 30
  y: 39.95681
  z: -295
- x: 30
  y: 38.24775
  z: -270
- x: 30
  y: 37.76558
  z: -245
- x: 30
  y: 35.50295
  z: -220
- x: 30
  y: 35.51385
  z: -195
- x: 30
  y: 38.19828
  z: -170
- x: 30
  y: 36.20507
  z: 30
- x: 30
  y: 31.76292
  z: 105
- x: 30
  y: 30.90093
  z: 130
- x: 30
  y: 32.61797
  z: 180
- x: 30
  y: 39.6938
  z: 255
- x: 30
  y: 39.67569
  z: 280
- x: 55.00001
  y: 40.94847
  z: -295
- x: 55
  y: 39.69865
  z: -270
- x: 55
  y: 36.80377
  z: -245
- x: 55.00001
  y: 36.84151
  z: -220
- x: 55
  y: 35.92886
  z: -195
- x: 55
  y: 36.76828
  z: -170
- x: 55
  y: 37.51641
  z: -145
- x: 55
  y: 40.69759
  z: -120
- x: 55
  y: 41.14732
  z: -95.00001
- x: 55.00001
  y: 40.68064
  z: -70
- x: 55
  y: 40.17382
  z: -45
- x: 55
  y: 32.47729
  z: 105
- x: 55
  y: 32.7748
  z: 130
- x: 55
  y: 33.15742
  z: 155
- x: 55
  y: 34.42975
  z: 180
- x: 55.00001
  y: 34.4982
  z: 205
- x: 55
  y: 37.46063
  z: 255
- x: 55
  y: 39.35406
  z: 280
- x: 79.99999
  y: 42.45523
  z: -295
- x: 79.99999
  y: 43.98831
  z: -270
- x: 79.99999
  y: 39.17913
  z: -245
- x: 79.99999
  y: 39.17206
  z: -220
- x: 80
  y: 38.20767
  z: -195
- x: 79.99999
  y: 39.21474
  z: -170
- x: 79.99999
  y: 38.05989
  z: -145
- x: 79.99999
  y: 38.31006
  z: -120
- x: 79.99999
  y: 39.3561
  z: -95
- x: 79.99999
  y: 39.4617
  z: -70
- x: 79.99999
  y: 38.80771
  z: -45
- x: 79.99999
  y: 37.77234
  z: -20
- x: 79.99999
  y: 37.65956
  z: 5
- x: 79.99999
  y: 36.80381
  z: 30
- x: 79.99999
  y: 35.62713
  z: 55
- x: 79.99999
  y: 33.94946
  z: 79.99999
- x: 79.99999
  y: 33.96138
  z: 105
- x: 79.99999
  y: 35.79285
  z: 205
- x: 79.99999
  y: 35.41909
  z: 230
- x: 80
  y: 38.72809
  z: 255
- x: 105
  y: 42.4864
  z: -295
- x: 105
  y: 42.2188
  z: -270
- x: 105
  y: 40.88842
  z: -245
- x: 105
  y: 40.13301
  z: -220
- x: 105
  y: 39.30206
  z: -195
- x: 105
  y: 38.896
  z: -170
- x: 105
  y: 38.57811
  z: -145
- x: 105
  y: 38.01597
  z: -120
- x: 105
  y: 38.19199
  z: -94.99999
- x: 105
  y: 38.99312
  z: -70
- x: 105
  y: 39.13802
  z: -45
- x: 105
  y: 37.21663
  z: -20
- x: 105
  y: 36.59584
  z: 5
- x: 105
  y: 36.26351
  z: 30
- x: 105
  y: 34.97665
  z: 55
- x: 105
  y: 35.02201
  z: 79.99999
- x: 105
  y: 37.29198
  z: 105
- x: 105
  y: 45.52909
  z: 180
- x: 105
  y: 36.08108
  z: 230
- x: 130
  y: 40.86088
  z: -270
- x: 130
  y: 37.27449
  z: -245
- x: 130
  y: 38.73293
  z: -220
- x: 130
  y: 39.38398
  z: -195
- x: 130
  y: 44.01006
  z: -170
- x: 130
  y: 43.42324
  z: -145
- x: 130
  y: 41.44146
  z: -120
- x: 130
  y: 38.95901
  z: -95
- x: 130
  y: 38.61697
  z: -70.00001
- x: 130
  y: 39.05201
  z: -45
- x: 130
  y: 37.28362
  z: 5
- x: 130
  y: 36.32896
  z: 55
- x: 130
  y: 35.12872
  z: 80
- x: 130
  y: 36.05622
  z: 105
- x: 130
  y: 37.17211
  z: 130
- x: 130
  y: 36.84903
  z: 230
- x: 155
  y: 43.97248
  z: -170
- x: 155
  y: 45.41275
  z: -145
- x: 155
  y: 43.45778
  z: -120
- x: 155
  y: 40.23891
  z: -94.99999
- x: 155
  y: 39.84809
  z: -70
- x: 155
  y: 41.33506
  z: -45
- x: 155
  y: 41.96473
  z: -20
- x: 155
  y: 40.71218
  z: 5
- x: 155
  y: 38.3872
  z: 55
- x: 155
  y: 36.20334
  z: 79.99999
- x: 155
  y: 35.88366
  z: 105
- x: 155
  y: 36.42617
  z: 130
- x: 155
  y: 39.03569
  z: 155
- x: 155
  y: 37.17078
  z: 230
- x: 180
  y: 27.15465
  z: -245
- x: 180
  y: 29.32398
  z: -220
- x: 180
  y: 42.78414
  z: -120
- x: 180
  y: 42.66312
  z: -95.00001
- x: 180
  y: 41.5024
  z: -69.99999
- x: 180
  y: 42.73182
  z: -45
- x: 180
  y: 41.51909
  z: -20
- x: 180
  y: 39.70839
  z: 5
- x: 180
  y: 38.81396
  z: 30
- x: 180
  y: 37.88999
  z: 55
- x: 180
  y: 36.47791
  z: 105
- x: 180
  y: 36.2908
  z: 130
- x: 180
  y: 37.43788
  z: 155
- x: 180
  y: 39.253
  z: 205
- x: 180
  y: 39.29189
  z: 230
- x: 180
  y: 40.62445
  z: 255
- x: 205
  y: 25.50167
  z: -245
- x: 205
  y: 25.69441
  z: -220
- x: 205
  y: 27.52253
  z: -195
- x: 205
  y: 30.52802
  z: -170
- x: 205
  y: 39.74386
  z: -120
- x: 205
  y: 42.67589
  z: -95
- x: 205
  y: 43.36325
  z: -69.99999
- x: 205
  y: 42.26233
  z: -45
- x: 205
  y: 40.69585
  z: -20
- x: 205
  y: 39.81227
  z: 5
- x: 205
  y: 39.26793
  z: 30
- x: 205
  y: 37.81692
  z: 105
- x: 205
  y: 36.78621
  z: 155
- x: 205
  y: 37.13189
  z: 180
- x: 205
  y: 37.88306
  z: 205
- x: 205
  y: 40.50613
  z: 230
- x: 230
  y: 24.28649
  z: -220
- x: 230
  y: 25.11833
  z: -195
- x: 230
  y: 26.8461
  z: -170
- x: 230
  y: 42.50287
  z: -70.00001
- x: 230
  y: 42.56503
  z: -45
- x: 230
  y: 42.24221
  z: -20
- x: 230
  y: 41.09222
  z: 5
- x: 230
  y: 41.10146
  z: 30
- x: 230
  y: 41.06731
  z: 55
- x: 230
  y: 40.68332
  z: 79.99999
- x: 230
  y: 40.63805
  z: 105
- x: 230
  y: 39.74363
  z: 130
- x: 230
  y: 38.63303
  z: 155
- x: 230
  y: 37.93818
  z: 205
- x: 255
  y: 25.48916
  z: -170
- x: 255
  y: 28.04906
  z: -145
- x: 255
  y: 30.35131
  z: -120
- x: 255
  y: 35.14872
  z: -95.00001
- x: 255
  y: 43.80061
  z: -45
- x: 255
  y: 43.06815
  z: -20
- x: 255
  y: 44.17879
  z: 55
- x: 255
  y: 44.54169
  z: 79.99999
- x: 255
  y: 44.08684
  z: 105
- x: 255
  y: 42.85846
  z: 130
- x: 255
  y: 40.85371
  z: 155
- x: 255
  y: 38.71951
  z: 180
- x: 280
  y: 25.44442
  z: -145
- x: 280
  y: 27.58395
  z: -120
- x: 280
  y: 30.76662
  z: -94.99999
- x: 280
  y: 39.42046
  z: -45
- x: 280
  y: 40.78562
  z: -20
- x: 280
  y: 49.00459
  z: 30
- x: 280
  y: 45.76683
  z: 55
- x: 280
  y: 46.29448
  z: 79.99999
- x: 280
  y: 46.26862
  z: 105
- x: 280
  y: 45.269
  z: 130
pointGroups:
  border:
    points:
    - x: 227.5725
      y: 40.43386
      z: 76.69669
    - x: 224.1885
      y: 26.76673
      z: -178.0284
    - x: -40.63074
      y: 33.66312
      z: -278.2096
    - x: -271.7734
      y: 42.05168
      z: -139.4849
    - x: -275.7368
      y: 41.88717
      z: 111.1489
    - x: -81.54823
      y: 31.02295
      z: 320.0767
  border_exit:
    points:
    - x: 144.0214
      y: 43.23071
      z: -130.8452
  midpoint:
    points:
    - x: 38.40898
      y: 44.90388
      z: -81.4615
  poi:
    points:
    - x: -73.79134
      y: 45.01355
      z: -228.4827
    - x: 98.34879
      y: 39.71746
      z: -213.8813
    - x: -4.919678
      y: 30.7965
      z: 81.73286
    - x: 174.1144
      y: 37.00076
      z: 75.48124
    - x: 15.79312
      y: 40.22472
      z: 269.645
    - x: -156.1219
      y: 42.03517
      z: 192.9045
    - x: -233.0814
      y: 33.52621
      z: -16.2683
  settlement:
    points:
    - x: -182.5191
      y: 31.74464
      z: -63.22707
    - x: 31.30223
      y: 35.39906
      z: -199.1544
    - x: 103.3857
      y: 36.10745
      z: 29.68462
layers:
- heightNormalized: 0
  temperature: 
  precipitationFactors:
    v:
      x: 0
      y: 0
      z: 0
  biome:
    tagsUsed: false
    keys:
    - mossy_dry
    tags: 
- heightNormalized: 0.1
  temperature: 
  precipitationFactors:
    v:
      x: 0.1
      y: 0.15
      z: 0.35
  biome:
    tagsUsed: true
    keys: 
    tags:
      mossy_green: true
- heightNormalized: 0.23
  temperature:
    f: -1
  precipitationFactors:
    v:
      x: 0
      y: 0
      z: 0
  biome:
    tagsUsed: false
    keys:
    - alpine_05_no_snow
    tags: 
- heightNormalized: 0.315
  temperature:
    f: -1
  precipitationFactors:
    v:
      x: 0
      y: 0
      z: 0
  biome:
    tagsUsed: false
    keys:
    - alpine_06
    tags: 
