hidden: false
color:
  r: 1
  g: 0
  b: 0
  a: 1
stepKey: mod_campaign_01
provinceKey: province_breakthrough_central
position:
  x: -160
  y: 0
  z: 0
branchKey: 
functionsGlobal:
- !Comment
  comment: Sample set of start functions. Most of functionality like that should be placed into the entry block under the campaign step, but putting functions here is a quick shortcut.
- !CreateUnit
  levelOffset: 0
  qualityTable: unitgroup_q3_rare
  factionBranch: 
  presetKey: vhc_mech_w1_mr_ar_shield
  presetTags: 
  memory: 
- !CreatePilot
  identification: 
  bio: 
  appearanceOverlay: 
  appearanceCustom: 
  appearancePresets:
  - unique_intro_pc
  memory: 
- !QuestStart
  questKey: province_selection
- !QuestProvinceCapture
  questMain: true
  questKey: 
- !OverworldInteractionStartFilter
  overrideOngoing: true
  tagsUsed: false
  keys:
  - mod_campaign_start
  tags: 
functionsBase: 
