hidden: false
color:
  r: 1
  g: 0
  b: 0
  a: 1
stepKey: mod_campaign_01
provinceKey: province_breakthrough_central
position:
  x: -160
  y: 0
  z: 0
branchKey: 
functionsGlobal:
- !Comment
  comment: Sample set of start functions. Most of functionality like that should be placed into the entry block under the campaign step, but putting functions here is a quick shortcut.
- !CreatePilot
  identification: 
  bio: 
  appearanceOverlay: 
  appearanceCustom: 
  appearancePresets: 
  memory: 
- !CreatePilot
  identification: 
  bio: 
  appearanceOverlay: 
  appearanceCustom: 
  appearancePresets: 
  memory: 
- !CreatePilot
  identification: 
  bio: 
  appearanceOverlay: 
  appearanceCustom: 
  appearancePresets: 
  memory: 
- !CreateUnit
  levelOffset: 0
  qualityTable: default_r1_common
  factionBranch: branch_army
  presetKey: vhc_mech_w1_lr_sniper
  presetTags: 
  memory: 
- !CreateUnit
  levelOffset: 0
  qualityTable: default_r1_common
  factionBranch: branch_army
  presetKey: vhc_mech_w2_mr_kinetic
  presetTags: 
  memory: 
- !CreateUnit
  levelOffset: 0
  qualityTable: default_r1_common
  factionBranch: branch_army
  presetKey: vhc_mech_w3_sr_shotgun_shield
  presetTags: 
  memory: 
- !ModifyResources
  resourceChanges:
  - key: supplies
    check: false
    checkStrict: false
    offset: false
    value: 1200
  - key: components_r2
    check: false
    checkStrict: false
    offset: false
    value: 20
  - key: camp_supplies
    check: false
    checkStrict: false
    offset: false
    value: 1
  - key: unit_token
    check: false
    checkStrict: false
    offset: false
    value: 1
- !QuestStart
  questKey: province_selection
- !QuestProvinceCapture
  questMain: true
  questKey: 
- !OverworldInteractionStartFilter
  overrideOngoing: true
  tagsUsed: false
  keys:
  - mod_campaign_start
  tags: 
functionsBase: 
