comment: 
ui:
  textName: {}
  textDesc: {}
  textNavHint: 
  textNavHeader: 
  textNavDesc: 
  iconNav: 
  textFromQuest: 
  mapHeader: 
  mapBackground:
    image: map_endgame
    size:
      x: 2048
      y: 2048
    color:
      r: 1
      g: 1
      b: 1
      a: 0.7
  mapLabels: 
  mapProvinceFilter:
    tagsUsed: true
    keys: 
    tags:
      mod_excluded: false
travelInteraction: 
entry:
  functionsGlobal:
  - !Log
    message: 'Campaign step 1: Entry'
  functionsBase: 
liberation:
  functionsGlobal:
  - !Log
    message: 'Campaign step 1: Liberation'
  functionsBase: 
progressDisplay: 
effects: 
branches:
- comment: 
  preferences:
    branchActiveExcluded: true
    modifiersUnique: true
    modifierVisitsTracked: false
  checksGlobal: 
  checksBase: 
  links:
  - comment: 
    checksGlobal: 
    checksBase: 
    stepKey: mod_campaign_02
    levelOffset: 
    branchKey: 
    searchRange:
      x: 0
      y: 0
    searchPriority: Closest
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        mod_excluded: false
    modifiers:
    - tagsUsed: true
      keys: 
      tags:
        type_positive: true
  - comment: 
    checksGlobal: 
    checksBase: 
    stepKey: mod_campaign_02
    levelOffset: 
    branchKey: 
    searchRange:
      x: 0
      y: 0
    searchPriority: Closest
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        mod_excluded: false
    modifiers:
    - tagsUsed: true
      keys: 
      tags:
        type_positive: true
  - comment: 
    checksGlobal: 
    checksBase: 
    stepKey: mod_campaign_02
    levelOffset: 
    branchKey: 
    searchRange:
      x: 0
      y: 0
    searchPriority: Closest
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        mod_excluded: false
    modifiers:
    - tagsUsed: true
      keys: 
      tags:
        type_positive: true
tags: 
