comment: 
ui:
  textName: {}
  textDesc: {}
  textNavHint: 
  textNavHeader: 
  textNavDesc: 
  iconNav: 
  textFromQuest: 
  mapHeader: 
  mapBackground:
    image: map_endgame
    size:
      x: 2048
      y: 2048
    color:
      r: 1
      g: 1
      b: 1
      a: 0.7
  mapLabels: 
  mapProvinceFilter: 
travelInteraction:
  tagsUsed: false
  keys:
  - mod_campaign_arrival_01
  tags: 
entry:
  functionsGlobal:
  - !ModifyMemoryBase
    changes:
    - change: Set
      key: campaign_countdown_base_length
      value: 24
      valueFromMemory: false
      valueFromMemoryKey: 
  - !ApplyProvinceArrivalEffects {}
  - !QuestStart
    questKey: mod_liberation
  functionsBase: 
liberation:
  functionsGlobal:
  - !Log
    message: 'Campaign step 2: Liberation'
  - !ModifyMemoryBase
    changes:
    - change: Offset
      key: campaign_progress_region_01
      value: 1
      valueFromMemory: false
      valueFromMemoryKey: 
  functionsBase: 
progressDisplay:
  memoryKey: mod_campaign_progress
  target: 8
effects: 
branches:
- comment: 
  preferences:
    branchActiveExcluded: true
    modifiersUnique: true
    modifierVisitsTracked: false
  checksGlobal: 
  checksBase: 
  links:
  - comment: 
    checksGlobal: 
    checksBase: 
    stepKey: mod_campaign_02
    levelOffset: 
    branchKey: 
    searchRange:
      x: 0
      y: 0
    searchPriority: Closest
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        group_breakthrough_central: false
        group_breakthrough_line: false
        group_capital: false
    modifiers:
    - tagsUsed: false
      keys:
      - gen_reward_parts
      tags: 
    - tagsUsed: false
      keys:
      - sp_liberation_easy
      tags: 
  - comment: 
    checksGlobal: 
    checksBase: 
    stepKey: mod_campaign_02
    levelOffset: 
    branchKey: 
    searchRange:
      x: 0
      y: 0
    searchPriority: Closest
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        group_breakthrough_central: false
        group_breakthrough_line: false
        group_capital: false
    modifiers:
    - tagsUsed: false
      keys:
      - gen_reward_parts
      tags: 
    - tagsUsed: false
      keys:
      - sp_liberation_easy
      tags: 
tags: 
