comment: 
ui:
  textName: {}
  textDesc: {}
  textNavHint: 
  textNavHeader: 
  textNavDesc: 
  iconNav: 
  textFromQuest: 
  mapHeader:
    color:
      r: 1
      g: 1
      b: 1
      a: 1
    mode: Fixed
    text: Liberated Fyrland
    textSector: 
    textKey: 
  mapBackground:
    image: map_endgame
    size:
      x: 2048
      y: 2048
    color:
      r: 1
      g: 1
      b: 1
      a: 0.7
  mapLabels: 
  mapProvinceFilter:
    tagsUsed: true
    keys: 
    tags:
      mod_excluded: false
travelInteraction: 
entry:
  functionsGlobal:
  - !Log
    message: 'Campaign step 3: Entry'
  - !ModifyMemoryBase
    changes:
    - change: Set
      key: campaign_countdown_base_length
      value: 20
      valueFromMemory: false
      valueFromMemoryKey: 
  - !QuestStart
    questKey: province_liberation
  - !ApplyProvinceArrivalEffects {}
  functionsBase: 
liberation:
  functionsGlobal:
  - !Log
    message: 'Campaign step 3: Liberation'
  - !ModifyMemoryBase
    changes:
    - change: Offset
      key: campaign_progress_region_04
      value: 1
      valueFromMemory: false
      valueFromMemoryKey: 
  - !OverworldInteractionStartFilter
    overrideOngoing: true
    tagsUsed: true
    keys: 
    tags:
      context_liberation: true
  functionsBase: 
progressDisplay:
  memoryKey: mod_campaign_progress
  target: 8
effects: 
branches:
- comment: 
  preferences:
    branchActiveExcluded: true
    modifiersUnique: true
    modifierVisitsTracked: false
  checksGlobal: 
  checksBase: 
  links:
  - comment: 
    checksGlobal: 
    checksBase: 
    stepKey: mod_campaign_03
    levelOffset: 
    branchKey: 
    searchRange:
      x: 0
      y: 0
    searchPriority: Closest
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        mod_excluded: false
    modifiers:
    - tagsUsed: true
      keys: 
      tags:
        type_positive: true
    - tagsUsed: true
      keys: 
      tags:
        type_negative: false
        type_special: false
  - comment: 
    checksGlobal: 
    checksBase: 
    stepKey: mod_campaign_03
    levelOffset: 
    branchKey: 
    searchRange:
      x: 0
      y: 0
    searchPriority: Closest
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        mod_excluded: false
    modifiers:
    - tagsUsed: true
      keys: 
      tags:
        type_negative: true
    - tagsUsed: true
      keys: 
      tags:
        type_positive: false
        type_special: false
tags: 
