comment: 
ui:
  textName: {}
  textDesc: {}
  textNavHint: 
  textNavHeader: {}
  textNavDesc: {}
  iconNav: 
  textFromQuest: 
  mapHeader: 
  mapBackground: 
  mapLabels: 
  mapProvinceFilter: 
travelInteraction: 
entry:
  functionsGlobal:
  - !Log
    message: 'Campaign step 1: Entry'
  functionsBase: 
liberation:
  functionsGlobal:
  - !Log
    message: 'Campaign step 2: Liberation'
  functionsBase: 
progressDisplay: 
effects: 
branches:
- comment: 
  preferences: 
  checksGlobal: 
  checksBase: 
  links:
  - comment:
      comment: Link to breakthrough province.
    checksGlobal: 
    checksBase: 
    stepKey: 10_breakthrough_line
    levelOffset: 
    branchKey: branch_reserves
    searchRange:
      x: 0
      y: 0
    searchPriority: None
    searchMode: Unvisited
    filter:
      tagsUsed: false
      keys:
      - province_breakthrough_line
      tags: 
    modifiers: 
  - comment:
      comment: Sidequest link. No level increase, same region. Available only if there's a non-liberated province and number of liberated provinces in this region is 1. Linked province has weaker units and a reward modifier.
    checksGlobal: 
    checksBase:
    - !OverworldValidateMemory
      check:
        method: RequireAll
        checks:
        - key: campaign_progress_region_01
          presenceDesired: false
          valueFromMemory: false
          valueFromMemoryKey: 
          valueCheck: Less
          value: 1
    stepKey: 02_side
    levelOffset:
      i: 0
    branchKey: branch_reserves
    searchRange:
      x: 0
      y: 0
    searchPriority: None
    searchMode: Unvisited
    filter:
      tagsUsed: true
      keys: 
      tags:
        group_liberation_01: true
    modifiers:
    - tagsUsed: false
      keys:
      - gen_reward_parts
      tags: 
    - tagsUsed: false
      keys:
      - sp_liberation_easy
      tags: 
tags: 
